### PR TITLE
Update Frigate to 0.12.0

### PR DESCRIPTION
**Pull request by kbarendrecht**

### CODE REVIEW

**Comment by toddrob99** [comment]
Just use the main image. Support is built-in now, and this repo is no longer necessary.

**Comment by TarheelGrad1998** [comment]
Not to intrude but...any more details on how to do this?

I just got my Coral today, after having experimented with 0.12.0 and CPU.  Frigate did not detect the Coral (yes with /dev/bus/usb exposed to the container).  So I assumed I'd need this repo and went looking if there was a 0.12.0 PR.  And now, I'm confused....

**Comment by toddrob99** [comment]
> Not to intrude but...any more details on how to do this?
> 
> I just got my Coral today, after having experimented with 0.12.0 and CPU. Frigate did not detect the Coral (yes with /dev/bus/usb exposed to the container). So I assumed I'd need this repo and went looking if there was a 0.12.0 PR. And now, I'm confused....

Scroll through the recent comments in #95. The last comment on there has a link to [official Frigate documentation](https://docs.frigate.video/frigate/installation/#synology-nas-on-dsm-7) for Synology DSM 7.

**Comment by TarheelGrad1998** [comment]
Thanks!  Got it...the hint I needed was here:
https://github.com/weltenwort/frigate-synology-dsm7/discussions/95#discussioncomment-5373788

Short version -- I'm still on DSM 6, and after adding /dev/bus/usb as a volume and not a device, it fired right up.

Thanks again!

**Comment by weltenwort** [comment]
Thanks for contributing! As others have pointed out this is not necessary anymore, if I'm not mistaken. So I'll turn this repo into a compose-file-only archive as soon as I get to it.

**Pull request closed without merging**
